name: Typo checks

on:
  workflow_dispatch:

  push:
    branches: 
    - staging

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.2.2

    - name: Lint typos
      uses: crate-ci/typos@b1a1ef3893ff35ade0cfa71523852a49bfd05d19
